### ISSUE TITLE
better visibility control than mixamo to blender

### ISSUE THREAD

**Issue by jameshdougherty** [shrekshao/gltf-avatar-threejs#9]
Hello, Noticed that this tool seems to do a much better job of creating a three JS friendly avatar than using Mixamo and importing/exporting through Blender, which in my testing of three different models left major gaps or disappeared altogether at some common viewing angles. 
Here's a Mixamo-thru-Blender model showing unwanted racoon mask:
![claire](https://user-images.githubusercontent.com/30966050/117586457-5762ee00-b0e6-11eb-817b-f4c63477ad51.jpg)
Here's eriri, bascially OK except for a small gap between the neck and suit:
![eriri](https://user-images.githubusercontent.com/30966050/117586458-57fb8480-b0e6-11eb-96e1-a89dcc881d3d.jpg)

Is there any possibility this tool will be expanded to include more models, animations and bones?

**Comment by shrekshao** [comment]
Thanks for finding this kind of  useful.
I don't have recent plan for updating this personally though...
Cheers

**Comment by jameshdougherty** [comment]
Thank you for the update. Sorry to hear there are no plans to further develop your excellent program. Any recommendation on how to find or create three js compatible avatars?

**Comment by shrekshao** [comment]
I don't know if there's anything handy. Or I wouldn't make this at first
